{% set name = "cpptrace" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeremy-rifkin/cpptrace/archive/v{{ version }}.tar.gz
  sha256: 7c2996f03d15f61016bc81fe7fa5220b1cc42498333c5c0e699ad2f96b918b96

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libdwarf
    - libdwarf-dev
    - zlib

test:
  requires:
    - cmake
    - {{ compiler("cxx") }}
    - ninja
  files:
    - test
  commands:
    - test -f $PREFIX/lib/libcpptrace${SHLIB_EXT}
    - test -f $PREFIX/include/cpptrace/cpptrace.hpp
    - test -f $PREFIX/lib/cmake/cpptrace/cpptrace-targets.cmake
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ./program

about:
  home: https://github.com/jeremy-rifkin/cpptrace
  summary: 'Simple, portable, and self-contained stacktrace library for C++11 and newer'
  description: |
    Cpptrace is a simple, portable, and self-contained C++ stacktrace library supporting C++11 and greater on Linux, macOS, and
    Windows including MinGW and Cygwin environments. The goal: Make stack traces simple for once.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremy-rifkin
