{% set name = "cpptrace" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeremy-rifkin/cpptrace/archive/v{{ version }}.tar.gz
  sha256: 2a03878112712105d908b94a3d33da65d81e035eca32a7a77410add05049d5e3

build:
  number: 0

  run_exports:
    - {{ pin_subpackage('cpptrace', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja        # [!win]
    - pkg-config   # [!win]
  host:
    - libdwarf     # [!win]
    - libdwarf-dev # [!win]
    - zlib         # [!win]

test:
  requires:
    - cmake
    - {{ compiler("cxx") }}
    - ninja                 # [!win]
  files:
    - test
  commands:
    - test -f $PREFIX/lib/libcpptrace${SHLIB_EXT}
    - test -f $PREFIX/include/cpptrace/cpptrace.hpp
    - test -f $PREFIX/include/cpptrace/basic.hpp
    - test -f $PREFIX/include/cpptrace/version.hpp
    - test -f $PREFIX/lib/cmake/cpptrace/cpptrace-targets.cmake
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ./program

about:
  home: https://github.com/jeremy-rifkin/cpptrace
  summary: 'Simple, portable, and self-contained stacktrace library for C++11 and newer'
  description: |
    Cpptrace is a simple, portable, and self-contained C++ stacktrace library supporting C++11 and greater on Linux, macOS, and
    Windows including MinGW and Cygwin environments. The goal: Make stack traces simple for once.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremy-rifkin
