{% set name = "cpptrace" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jeremy-rifkin/cpptrace/archive/v{{ version }}.tar.gz
  sha256: 2a03878112712105d908b94a3d33da65d81e035eca32a7a77410add05049d5e3

build:
  number: 0

  run_exports:
    - {{ pin_subpackage('cpptrace', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja        # [unix]
    - pkg-config   # [unix]
  host:
    - libdwarf     # [unix]
    - libdwarf-dev # [unix]
    - zlib         # [unix]

test:
  requires:
    - cmake
    - {{ compiler("cxx") }}
    - ninja                 # [unix]
  files:
    - test
  commands:
    - test -f $PREFIX/lib/libcpptrace${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/cpptrace/cpptrace.hpp  # [unix]
    - test -f $PREFIX/include/cpptrace/basic.hpp  # [unix]
    - test -f $PREFIX/include/cpptrace/version.hpp  # [unix]
    - test -f $PREFIX/lib/cmake/cpptrace/cpptrace-targets.cmake  # [unix]
    - cd test # [unix]
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug # [unix]
    - cmake --build . --config Debug # [unix]
    - ./program # [unix]


    - echo printbug_X  # [win]
    - SET  # [win]
    - echo %PREFIX%  # [win]
    - echo printbug_Z  # [win]
    - "if not exist %PREFIX%\\lib\\cpptrace.lib (echo Not found: %PREFIX%\\lib\\cpptrace.lib & exit 1)"  # [win]
    - echo printbug_A  # [win]
    - "if not exist %PREFIX%\\bin\\cpptrace.dll (echo Not found: %PREFIX%\\bin\\cpptrace.dll & exit 1)"  # [win]
    - echo printbug_B  # [win]
    - "if not exist %PREFIX%\\include\\cpptrace\\cpptrace.hpp (echo Not found: %PREFIX%\\include\\cpptrace\\cpptrace.hpp & exit 1)"  # [win]
    - echo printbug_C  # [win]
    - "if not exist %PREFIX%\\include\\cpptrace\\basic.hpp (echo Not found: %PREFIX%\\include\\cpptrace\\basic.hpp & exit 1)"  # [win]
    - echo printbug_D  # [win]
    - "if not exist %PREFIX%\\include\\cpptrace\\version.hpp (echo Not found: %PREFIX%\\include\\cpptrace\\version.hpp & exit 1)"  # [win]
    - echo printbug_E  # [win]
    - "if not exist %PREFIX%\\lib\\cmake\\cpptrace\\cpptrace-targets.cmake (echo Not found: %PREFIX%\\lib\\cmake\\cpptrace\\cpptrace-targets.cmake & exit 1)"  # [win]
    - echo printbug_F  # [win]
    - cd test  # [win]
    - echo printbug_G  # [win]
    - cmake .  # [win]
    - echo printbug_H  # [win]
    - cmake --build . --config Debug  # [win]
    - echo printbug_I  # [win]
    - .\\program.exe  # [win]
    - echo printbug_J  # [win]

about:
  home: https://github.com/jeremy-rifkin/cpptrace
  summary: 'Simple, portable, and self-contained stacktrace library for C++11 and newer'
  description: |
    Cpptrace is a simple, portable, and self-contained C++ stacktrace library supporting C++11 and greater on Linux, macOS, and
    Windows including MinGW and Cygwin environments. The goal: Make stack traces simple for once.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremy-rifkin
